# Generated by Django 5.1.4 on 2025-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_firstname_alter_order_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Выполнен'), ('in_transit', 'В пути'), ('processing', 'В обработке'), ('cancelled', 'Отменен'), ('pending_payment', 'Не оплачен')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьерская доставка')], default='courier', max_length=20),
        ),
    ]
