# Generated by Django 5.1.4 on 2025-05-01 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_firstname_alter_user_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона может содержать только цифры",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
