# Generated by Django 5.1.4 on 2025-02-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='filter_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название для фильтра'),
        ),
    ]
