# Generated by Django 5.1.4 on 2025-02-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_filterattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterattribute',
            old_name='attributes',
            new_name='attribute',
        ),
    ]
