# Generated by Django 5.1.4 on 2025-03-19 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_country_remove_user_address_remove_user_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('in_store', 'Оплата в магазине')], default='card', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Оплачено'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('canceled', 'Отменено')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьерская доставка'), ('cdek', 'Доставка через СДЭК')], default='courier', max_length=20)),
                ('delivery_cost', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('firstname', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы', regex='^[А-Яа-яЁёA-Za-z\\s\\-]+$')])),
                ('lastname', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Фамилия может содержать только буквы', regex='^[А-Яа-яЁёA-Za-z\\s\\-]+$')])),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('mail', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Номер телефона может содержать только цифры', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
