# Generated by Django 5.1.4 on 2025-02-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attribute_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_filterable', models.BooleanField(default=True)),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_attributes', to='product.attribute', verbose_name='Атрибут')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_attributes', to='product.category', verbose_name='Категория')),
            ],
        ),
    ]
