# Generated by Django 5.1.4 on 2025-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_filterattribute_options_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
    ]
